### ISSUE TITLE
Customer serializer needed?

### ISSUE THREAD

**Issue by m19** [bmac/ember-data-sails-adapter#20]
Hi,

I'm toying around with Sails.JS and Ember. I'm using Sails 0.10.

Is it intended behaviour I need to change my payload with Ember? I'm using a couple default created models and controllers by Sails.

```
App.GameSerializer = DS.RESTSerializer.extend({
    extractSingle: function(store, type, payload, id, requestType) {

        var newPayload = {  };

        newPayload.game = payload;
        payload = newPayload;

        return this._super(store, type, payload, id, requestType);
    }
});
```

EDIT1:
One a second note, my question is alot shorter: Ember expects the json to be in the http://jsonapi.org/ but the default Sails is alot different. Are there any "easy" solutions?

EDIT2: I changed a serializer I found. Answer here: http://stackoverflow.com/a/22992836/2904210

EDIT3:
This is still not working:
If a send a PUT request to http://127.0.0.1:1337/api/game/1 updating something sails emits a game object only containing the update and updatedAt. This of course throws an error since it doesn't include a ID. 

```
 Uncaught Error: Assertion Failed: You must include an `id` in a hash passed to `push` 
```

Also, are there maybe any examples using Sails + this adapter + Ember?

**Comment by Glavin001** [comment]
@bmac was the serializer used here ever updated to that improved serializer / or something else?

**Comment by bmac** [comment]
@Glavin001 There have been some minor changes but over all this library is still in need of some love. I'd suggest you take a look at https://github.com/huafu/ember-data-sails if you are currently using ember-cli.
